// netlify.toml
[build]
  command = "npm run build"
  publish = "/"
  base = "/"

[context.production.environment]
  REACT_APP_KAKAO_REST_API_KEY=5f72e5b42e15db7003f632d17249d64d
  REACT_APP_REDIRECT_URI_AUTH=http://192.168.219.100:3000/auth/kakao
  REACT_APP_REDIRECT_URI_LOGIN=http://192.168.219.100:3000/auth/kakaologin
  REACT_APP_CLIENT_SECRET=GADzoNdziI1Gki0SeQTSD6lcpc2UAZpW
  REACT_APP_JS_KEY=8ebbcb2889a52678d9529c56d46847fa
